rm ./ANNdroid/src/*.class
rm ./ANNdroid/src/panels/*.class
rm ./ANNdroid/src/util/*.class
rm ./ANNdroid/src/objects/*.class
rm ./ANNdroid/src/events/*.class
rm ./ANNdroid/src/custom_swing/*.class
rm ./ANNdroid/src/ai/aimaker/*.class
rm ./ANNdroid/src/ai/ann/*.class
rm ./ANNdroid/src/ai/search/*.class